language: c

compiler:
  - clang
  - gcc

script: autoreconf -vi && ./configure && make

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "K79kWmyEF+CRFa7vb/Nq2gNX3VzqUJY45xP3XRPlSm6BtvpHhJLENX5V+nEkFhFgr0taIXG3eyFDW9rh7xFTUdiXLMHI5bJuq1HofRXTHTo5fmEjzpsp7LJyv14Tab4PA0oCH1eTz/qTEunzNIXh1GilTrCcxPIkF6MIq95Hl9lQSYkNPUcomVqcmJejXafHccrAE/IcqaO4BryKXmoT+U07TQOWmEpBY3exNbXfDMoUOQNfQihzgYIjEiFWI2wQ+F2U8YnrfE4N4EuVNbQAwI8MLRixb1dCyBVbgGRewvZB9RWuzSVT6fDcKtcjPsPH4KH8Is8y9joNYrEb7blWS0vulDBIqm4Bs7MSL91V1kxKwIj5tGsa9bVfIgN/0CKGWIgUDLiiQTamSfKfiPbMYPStABHePShRjrfxVfUD8unzyVPf04Y5K+LKPPApaqkPLy3wiVbEVVgXx/5fochOlmxwPtcAfcs0lOSlvV70Go24bS78uCzVCclfbDEAeMvEixdPsP6+fMAC255fC2Kd4SBRLbS9tIIJkeo8MxrP+EW+mAiognHemoml+RWePA0Jd5Oc5xPFPicbS2XFcopKWuuQEDi/08ve9kjts2ImrSlG8yGH+BMOzjyOUEy3h9LEdGmeZJ2AX3Q8UP2Id9qZwmnh/s+n3tKC3sdsjN4ygvI="

before_install:
      - echo -n | openssl s_client -connect scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-

addons:
  coverity_scan:
    project:
      name: "ssvb/xf86-video-fbturbo"
      description: "Build submitted via Travis CI"
    notification_email: siarhei.siamashka@gmail.com
    build_command_prepend: "autoreconf -vi && ./configure && make clean"
    build_command:   "make -j 4"
    branch_pattern: coverity_scan
  apt:
    packages:
      - build-essential
      - xorg-dev
      - xutils-dev
      - x11proto-dri2-dev
      - libltdl-dev
      - libtool
      - automake
      - libdrm-dev
