language: c

compiler:
  - clang
  - gcc

addons:
  apt:
    packages:
      - build-essential
      - xorg-dev
      - xutils-dev
      - x11proto-dri2-dev
      - libltdl-dev
      - libtool
      - automake
      - libdrm-dev

script: autoreconf -vi && ./configure && make
