language: c
compiler: gcc

script:
  - git clone https://github.com/linux-sunxi/libump.git && cd libump && autoreconf -i && ./configure --prefix=/usr && make && sudo make install && cd .. && autoreconf -vi && ./configure && make

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "RqvO6HqSO0vpKqcO5YHWm7ds/1bVx6uRaiUhKPJIRQGQ+iCE41n8HWh+2MOsGll0YADgDawfhenBcf1ttC7USybliKnhRBw70+UskIGOpGdx85OB1mQWxgNJC/pH+9Kj84iRnMyjxfm6tDhPwIxLWO1SzzAZz1QHK6wS7tDKBVn9wHwqxbz4L5hhHu+Wc7F3ZwtQbGylHhVSmTm7gPdFlmTFBqwSClpeZM3AaivOEhRiwVJq4gO2o9HWt8L7yIjCbRc5kW8gJkKkC8/iBwp6BYSVgE8JjVN1HbZj5kSvUbBP5LBm5FJR9ros/eXGQ7mhMezfufCted+leL58sBsriW/0a2NvCjuaijALWh15kLGF8NnQZk29cgog1/dr7poXWxY0w4c4qzF3gr+jxJyZiXym2iBgNKPqCvm2Pcmmo3V2iO+5Wxv6u36++/jrwD+XHs2bb7bdhCInbxf1XsDngPEH/3A8+21754dvFuTMQYD73pnA6mE2OET2ZN9/sOWT9eiBxmtRIc6h+Pslr7RYlvO52KFvPAGKHduI4vsh0l684w8nadOSykrEwNtzpA99yeqYfc0veW6CJZE5KlGcEKwVHITAxcToOKQyAVVOkdQichOvM3D8DJmu8EtJ+LrfsMzSQUTqrpZPmtNK2mTj63oNPBIjpKxHHgrSovZPftM="

before_install:
      - echo -n | openssl s_client -connect scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-

addons:
  coverity_scan:
    project:
      name: "ssvb/xf86-video-fbturbo"
      description: "Build submitted via Travis CI"
    notification_email: siarhei.siamashka@gmail.com
    build_command_prepend: "git clone https://github.com/linux-sunxi/libump.git && cd libump && autoreconf -i && ./configure --prefix=/usr && make && sudo make install && cd .. && autoreconf -vi && ./configure && make clean"
    build_command:   "make -j 4"
    branch_pattern: coverity_scan
  apt:
    packages:
      - build-essential
      - xorg-dev
      - xutils-dev
      - x11proto-dri2-dev
      - libltdl-dev
      - libtool
      - automake
      - libdrm-dev
